"""Export author-entered ratings verbatim; no automatic semantic grading."""
import argparse
import csv
import hashlib
import json
from pathlib import Path

from validate_unmet_review import validate

ROOT = Path(__file__).resolve().parents[1]
FOLDER = ROOT / 'Paper/human-unmet-review'


def tex(value):
    substitutions = {'\\': r'\textbackslash{}', '&': r'\&', '%': r'\%',
                     '$': r'\$', '#': r'\#', '_': r'\_', '{': r'\{', '}': r'\}',
                     '~': r'\textasciitilde{}', '^': r'\textasciicircum{}',
                     '<': r'\textless{}', '>': r'\textgreater{}'}
    return ''.join(substitutions.get(c, c) for c in value)


def build():
    status = validate(review_name='semantic_review.csv')
    assert status['complete'], 'Do not export an incomplete author form'
    source = FOLDER / 'semantic_review.csv'
    with source.open(encoding='utf-8-sig', newline='') as f:
        rows = list(csv.DictReader(f))
    rows.sort(key=lambda r: int(r['case']))
    text = [r'''% Generated by scripts/summarize_semantic_review.py; author labels unchanged.
\subsubsection{未充足条件応答に対する著者の確認記録}\label{app:author_unmet_review}
表\ref{tab:author_unmet_review}は，表\ref{tab:unmet_internal}の未充足条件応答そのものを対象とした著者ugaiによる2026年9月7日の記入である．同じ8候補について要求メッセージ全文，応答全文，抽出辞書，関連する完全グラフの状態・関係を提示した．採点基準は，未充足条件の列挙と網羅が妥当なら「正しい」，妥当な部分と誤り・欠落があれば「一部正しい」，主要な説明が不適切なら「誤り」，資料でも判断できなければ「判断不能」とした．根拠・評価者・日付も記録した．表の根拠は著者記入のまま示し，AIによる修正文や正解ラベルへ置き換えていない．

評価者は最初に応答文と現在状態の一致で採点したと申告したため，その票（正しい2件・誤り6件）と未充足条件としての再確認票を分けた．再確認ではAI支援による採点基準の説明と個別例の整合性照会を複数回行い，著者がラベル・根拠を修正した．従って同一著者の支援付き事例確認であり，独立評価・盲検評価ではない．判定応答を対象にした全8件「判断不能」の票とも合算しない．
\begin{table*}[tb]
\caption{未充足条件応答への著者記入ラベルと根拠（番号は表\ref{tab:unmet_internal}と共通）}\label{tab:author_unmet_review}
\centering\small
\begin{tabular}{rlp{.78\textwidth}}
\hline
番号 & 著者ラベル & 著者記入の根拠 \\
\hline''']
    for row in rows:
        text.append(' & '.join(tex(row[k]) for k in ('case', 'review_label', 'evidence')) + r' \\')
    text.append(r'''\hline
\end{tabular}
\end{table*}

この記入結果は説明品質の正解ラベル集合として確定したものではない．例えば4番は非保持を示す根拠，6・8番は近接が必要という根拠を記しているが，それだけでは保持・近接を未充足条件として列挙した応答を誤りとする理由を十分に説明しない．評価対象の読み方と根拠の対応に曖昧さが残り，第三者による裁定も行っていない．著者の判断記録として提示するにとどめ，この比率を説明の確定正解率としたり，全59候補への推定値やVH実行可能性の正解率としたりしない．評価者間一致率も算出しない．
''')
    counts = status['labels']
    total_sentence = '著者の最終記入は' + '，'.join(f'{name}{counts.get(name, 0)}件' for name in ('正しい', '一部正しい', '誤り', '判断不能')) + 'である．\n'
    text[0] = text[0].replace(r'\begin{table*}[tb]', total_sentence + r'\begin{table*}[tb]')
    manifest = {'target_phase': 'unmet', 'author_records_received': len(rows),
                'label_counts': counts, 'evaluator': sorted({r['evaluator'] for r in rows}),
                'recorded_dates': sorted({r['date'] for r in rows}),
                'assessment_type': 'same-author review after AI-assisted rubric clarification',
                'independent_or_blinded': False, 'semantic_gold_standard_established': False,
                'human_labels_generated_or_changed_by_exporter': False,
                'sources_sha256': {str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest()
                                   for p in (source, FOLDER / 'review_blank.csv', Path(__file__),
                                             ROOT / 'scripts/validate_unmet_review.py')}}
    return {ROOT / 'Paper/appendix-human-review.tex': '\n'.join(text),
            FOLDER / 'recorded_results.json': json.dumps(manifest, ensure_ascii=False, indent=2) + '\n'}


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in build().items():
        if args.check:
            assert path.read_text() == content, str(path)
        else:
            path.write_text(content)
        print(('checked' if args.check else 'exported'), path.relative_to(ROOT))
